scalar DateTime

type Order {
	id: ID!
	orderProducts: [OrderProduct!]!
	amount: Float!
	orderDate: DateTime!
	user: User!
}

type OrderProduct {
  id: ID!
  quantity: Int!
  product: Product!
  order: Order!
}
